#define BODY(fast) \
   GEO_SWITCH_CASE(20, geo_switch_anim_state), \
   GEO_OPEN_NODE(), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041F0##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_06004208##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_06004220##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_06004208##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041F0##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041F0##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_06004208##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_06004220##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_06004208##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041F0##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
      GEO_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_060041D8##fast), \
   GEO_CLOSE_NODE()

// 0x0D00001C
const GeoLayout mr_i_iris_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(2, geo_switch_fast),
      GEO_OPEN_NODE(),
         BODY(),
         BODY(_fast),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

#undef BODY
