#include "src/game/envfx_snow.h"

const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_3___eyes_look_left_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_4___eyes_look_right_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_5___eyes_look_up_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_6___eyes_look_down_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eyes_dead_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_head_capless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_hand_open_left_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_hand_open_right_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_004_switch_option_hand_peace_right_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_005_switch_option_hand_cap_right_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_006_switch_option_hand_wing_cap_right_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, mario_006_switch_option_hand_wing_cap_wings_right_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_3___eyes_look_left_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_4___eyes_look_right_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_5___eyes_look_up_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_6___eyes_look_down_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eyes_dead_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_jump_mario_head_capless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_jump_mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_hand_open_left_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_jump_mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_hand_open_right_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_jump_mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_004_switch_option_hand_peace_right_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_jump_mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_005_switch_option_hand_cap_right_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_jump_mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_006_switch_option_hand_wing_cap_right_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_006_switch_option_hand_wing_cap_wings_right_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_head_capless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_hand_open_left_mesh_layer_1_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_hand_open_right_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_004_switch_option_hand_peace_right_mesh_layer_1_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_005_switch_option_hand_cap_right_mesh_layer_1_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_006_switch_option_hand_wing_cap_right_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_006_switch_option_hand_wing_cap_wings_right_mesh_layer_4_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_pelvis_mesh_layer_1_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_chest_mesh_layer_1_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_head_capless),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_L_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_R_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_L_mesh_layer_1_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_L_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_L_mesh_layer_1_mat_override_metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_left_hand_open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_R_mesh_layer_1_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_R_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_R_mesh_layer_1_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_open),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_peace),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_cap),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1_jump_mario_003_alpha_switch_case_opt1_jump_mario_right_hand_wing_cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_L_mesh_layer_1_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_L_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_foot_L_mesh_layer_1_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_R_mesh_layer_1_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_R_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_R_mesh_layer_1_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_face_1___eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_face_2___eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_face_3___eyes_look_left_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_face_4___eyes_look_right_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_face_5___eyes_look_up_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_face_6___eyes_look_down_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1_mat_override_face_7___eyes_dead_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_env_map),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_pelvis_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_chest_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt1),
													GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt2),
													GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt3),
													GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt4),
													GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt5),
													GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt6),
													GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt7),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_jump_mario_head_capless),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_L_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_R_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_L_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_L_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_jump_mario_left_hand_open),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_R_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_R_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_jump_mario_right_hand_open),
												GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_jump_mario_right_hand_peace),
												GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_jump_mario_right_hand_cap),
												GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_jump_mario_right_hand_wing_cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_L_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_foot_L_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_R_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_R_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_003_alpha_switch_case_opt1_002_metal_switch_case_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_head_capless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_hand_open_left_mesh_layer_1_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_hand_open_right_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_004_switch_option_hand_peace_right_mesh_layer_1_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_005_switch_option_hand_cap_right_mesh_layer_1_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_006_switch_option_hand_wing_cap_right_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, mario_006_switch_option_hand_wing_cap_wings_right_mesh_layer_4_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_pelvis_mesh_layer_1_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_chest_mesh_layer_1_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_head_capless),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_L_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_R_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_L_mesh_layer_1_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_L_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_L_mesh_layer_1_mat_override_metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_left_hand_open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_R_mesh_layer_1_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_R_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_R_mesh_layer_1_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_open),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_peace),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_cap),
										GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1_jump_mario_right_hand_wing_cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_L_mesh_layer_1_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_L_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_foot_L_mesh_layer_1_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_R_mesh_layer_1_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_R_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_R_mesh_layer_1_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_face_1___eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_face_2___eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_face_3___eyes_look_left_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_face_4___eyes_look_right_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_face_5___eyes_look_up_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_face_6___eyes_look_down_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1_mat_override_face_7___eyes_dead_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_alpha),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_env_map),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_pelvis_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_chest_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt1),
																	GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt2),
																	GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt3),
																	GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt4),
																	GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt5),
																	GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt6),
																	GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt0_capless_switch_opt0_face_switch_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, mario_head_capless),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_L_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_R_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_L_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_L_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_L_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, mario_left_hand_open),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_R_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_R_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_R_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, mario_right_hand_open),
																GEO_BRANCH(1, mario_right_hand_peace),
																GEO_BRANCH(1, mario_right_hand_cap),
																GEO_BRANCH(1, mario_right_hand_wing_cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_L_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_L_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_foot_L_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_R_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_R_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_R_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, mario_003_alpha_switch_case_opt0_002_metal_switch_case_opt1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, mario_003_alpha_switch_case_opt1),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
				GEO_ASM(3, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 3945, 0, 0, NULL),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
