#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "common0.h"

#include "blue_coin_switch/geo.inc.c"
// Hmm, this is included earlier.
#include "test_platform/geo.inc.c"
#include "amp/geo.inc.c"
#include "cannon_lid/geo.inc.c"
#include "cannon_base/geo.inc.c"
#include "cannon_barrel/geo.inc.c"
#include "chuckya/geo.inc.c"
#include "purple_switch/geo.inc.c"
#include "checkerboard_platform/geo.inc.c"
#include "heart/geo.inc.c"
#include "flyguy/geo.inc.c"
#include "breakable_box/geo.inc.c"
#include "bowling_ball/geo.inc.c"
#include "exclamation_box/geo.inc.c"
#include "goomba/geo.inc.c"
#include "bobomb/geo.inc.c"
#include "metal_box/geo.inc.c"
#include "exclamation_box_outline/geo.inc.c"
#include "koopa_shell/geo.inc.c"

#include "thwomp/geo.inc.c"
#include "heave_ho/geo.inc.c"
#include "bully/geo.inc.c"
#include "spindrift/geo.inc.c"
#include "snowman/geo.inc.c"
#include "boo/geo.inc.c"
#include "lakitu_enemy/geo.inc.c"
#include "spiny_egg/geo.inc.c"
#include "spiny/geo.inc.c"
#include "skeeter/geo.inc.c"
#include "piranha_plant/geo.inc.c"
#include "whomp/geo.inc.c"
#include "mr_i_eyeball/geo.inc.c"
#include "mr_i_iris/geo.inc.c"
#include "snufit/geo.inc.c"
#include "scuttlebug/geo.inc.c"
#include "bubba/geo.inc.c"

#include "toad/geo.inc.c"
