#ifndef SEQ_IDS_H
#define SEQ_IDS_H

#define SEQUENCE_NONE 0xFF

#define SEQ_MENU_GAME_OVER (SEQ_MENU_TITLE_SCREEN_GAMEOVER)

enum SeqId {
    SEQ_SOUND_PLAYER,                 // 0x00
    SEQ_EVENT_CUTSCENE_COLLECT_STAR,  // 0x01
    SEQ_MENU_STAR_SELECT,             // 0x02
    SEQ_EVENT_KOOPA_MESSAGE,          // 0x03
    SEQ_EVENT_CUTSCENE_CREDITS,       // 0x04
    SEQ_EVENT_SOLVE_PUZZLE,           // 0x05
    SEQ_EVENT_TOAD_MESSAGE,           // 0x06
    SEQ_EVENT_CUTSCENE_VICTORY,       // 0x07
    SEQ_EVENT_CUTSCENE_ENDING,        // 0x08
    SEQ_EVENT_CUTSCENE_COLLECT_KEY,   // 0x09
    SEQ_EVENT_CUTSCENE_STAR_SPAWN,    // 0x0A
    SEQ_EVENT_HIGH_SCORE,             // 0x0B
    SEQ_EVENT_ENDLESS_STAIRS,         // 0x0C
    SEQ_EVENT_MERRY_GO_ROUND,         // 0x0D
    SEQ_MENU_TITLE_SCREEN,            // 0x0E
    SEQ_LEVEL_GRASS,                  // 0x0F
    SEQ_LEVEL_INSIDE_CASTLE,          // 0x10
    SEQ_LEVEL_WATER,                  // 0x11
    SEQ_LEVEL_HOT,                    // 0x12
    SEQ_LEVEL_BOSS_KOOPA,             // 0x13
    SEQ_LEVEL_SNOW,                   // 0x14
    SEQ_LEVEL_SLIDE,                  // 0x15
    SEQ_LEVEL_SPOOKY,                 // 0x16
    SEQ_EVENT_PIRANHA_PLANT,          // 0x17
    SEQ_LEVEL_UNDERGROUND,            // 0x18
    SEQ_EVENT_POWERUP,                // 0x19
    SEQ_EVENT_METAL_CAP,              // 0x1A
    SEQ_LEVEL_KOOPA_ROAD,             // 0x1B
    SEQ_EVENT_RACE,                   // 0x1C
    SEQ_EVENT_BOSS,                   // 0x1D
    SEQ_LEVEL_BOSS_KOOPA_FINAL,       // 0x1E
    SEQ_MENU_FILE_SELECT,             // 0x1F
    SEQ_EVENT_POWERUP_SHELL,
    SEQ_MENU_TITLE_SCREEN_GAMEOVER,
    SEQ_LEVEL_22,
    SEQ_LEVEL_23,
    SEQ_LEVEL_24,
    SEQ_LEVEL_25,
    SEQ_LEVEL_26,
    SEQ_LEVEL_27,
    SEQ_LEVEL_28,
    SEQ_LEVEL_29,
    SEQ_LEVEL_2A,
    SEQ_LEVEL_2B,
    SEQ_LEVEL_2C,
    SEQ_LEVEL_2D,
    SEQ_LEVEL_2E,
    SEQ_LEVEL_2F,
    SEQ_LEVEL_30,
    SEQ_LEVEL_31,
    SEQ_LEVEL_32,
    SEQ_LEVEL_33,
    SEQ_LEVEL_34,
    SEQ_LEVEL_35,
    SEQ_LEVEL_36,
    SEQ_LEVEL_37,
    SEQ_LEVEL_38,
    SEQ_LEVEL_39,
    SEQ_LEVEL_3A,
    SEQ_LEVEL_3B,
    SEQ_LEVEL_3C,
    SEQ_LEVEL_3D,
    SEQ_LEVEL_3E,
    SEQ_LEVEL_3F,
    SEQ_LEVEL_40,
    SEQ_LEVEL_41,
    SEQ_LEVEL_42,
    SEQ_LEVEL_43,
    SEQ_LEVEL_44,
    SEQ_LEVEL_45,
    SEQ_LEVEL_46,
    SEQ_LEVEL_47,
    SEQ_LEVEL_48,
    SEQ_LEVEL_49,
    SEQ_LEVEL_4A,
    SEQ_LEVEL_4B,
    SEQ_LEVEL_4C,
    SEQ_LEVEL_4D,
    SEQ_LEVEL_4E,
    SEQ_LEVEL_4F,
    SEQ_LEVEL_50,
    SEQ_LEVEL_51,
    SEQ_LEVEL_52,
    SEQ_LEVEL_53,
    SEQ_LEVEL_54,
    SEQ_LEVEL_55,
    SEQ_LEVEL_56,
    SEQ_LEVEL_57,
    SEQ_LEVEL_58,
    SEQ_LEVEL_59,
    SEQ_LEVEL_5A,
    SEQ_LEVEL_5B,
    SEQ_LEVEL_5C,
    SEQ_LEVEL_5D,
    SEQ_LEVEL_5E,
    SEQ_LEVEL_5F,
    SEQ_LEVEL_60,
    SEQ_LEVEL_61,
    SEQ_LEVEL_62,
    SEQ_LEVEL_63,
    SEQ_LEVEL_64,
    SEQ_LEVEL_65,
    SEQ_LEVEL_66,
    SEQ_LEVEL_67,
    SEQ_LEVEL_68,
    SEQ_LEVEL_69,
    SEQ_LEVEL_6A,
    SEQ_LEVEL_6B,
    SEQ_LEVEL_6C,
    SEQ_LEVEL_6D,
    SEQ_LEVEL_6E,
    SEQ_LEVEL_6F,
    SEQ_LEVEL_70,
    SEQ_LEVEL_71,
    SEQ_LEVEL_72,
    SEQ_LEVEL_73,
    SEQ_LEVEL_74,
    SEQ_LEVEL_75,
    SEQ_LEVEL_76,
    SEQ_LEVEL_77,
    SEQ_LEVEL_78,
    SEQ_LEVEL_79,
    SEQ_LEVEL_7A,
    SEQ_LEVEL_7B,
    SEQ_LEVEL_7C,
    SEQ_LEVEL_7D,
    SEQ_LEVEL_7E,
    SEQ_LEVEL_7F,
    SEQ_LEVEL_80,
    SEQ_LEVEL_81,
    SEQ_LEVEL_82,
    SEQ_LEVEL_83,
    SEQ_LEVEL_84,
    SEQ_LEVEL_85,
    SEQ_LEVEL_86,
    SEQ_LEVEL_87,
    SEQ_LEVEL_88,
    SEQ_LEVEL_89,
    SEQ_LEVEL_8A,
    SEQ_LEVEL_8B,
    SEQ_LEVEL_8C,
    SEQ_LEVEL_8D,
    SEQ_LEVEL_8E,
    SEQ_LEVEL_8F,
    SEQ_LEVEL_90,
    SEQ_LEVEL_91,
    SEQ_LEVEL_92,
    SEQ_LEVEL_93,
    SEQ_LEVEL_94,
    SEQ_LEVEL_95,
    SEQ_LEVEL_96,
    SEQ_LEVEL_97,
    SEQ_LEVEL_98,
    SEQ_LEVEL_99,
    SEQ_COUNT
};

#endif // SEQ_IDS_H
